version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "8080:80"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://localhost:8080'; gitlab_rails['gitlab_shell_ssh_port'] = 2222"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092

  agent:
    build: .
    depends_on:
      - gitlab
      - postgres
      - kafka
    environment:
      - GITLAB_PRIVATE_TOKEN=your-private-token
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092